---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Malcolm Gittens"
pagetitle: "L01 Malcolm Gittens"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Malcolm's Github](https://github.com/stat301-3-2026-spring/l01-review-MalcolmGittens)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution
**1. Define the Problem**

Regression or Classification 

**2. Collect the Data**

Explore aspects like misingness and variable types

**3. Process the data**

Feature engineer and handle and data issues found
Potentially create new features for data 

**4. Split the data**

Divide the data into training and testing sets

**5. Choose a model**

This could be KNN, RF, BT, Linear, Log, etc. 

**6. Train the selected model**

Fit the model to the data

**7. Tune Hyper parameters**

Essentially optimize model settings: Cross-validation and Grid 

**8. Evaluate Model Performance**

Use test data and use a metric (R^2, Accuracy, etc.) to see if the model works well 

**9. Interpret the model**

Check for Overfitting or Underfitting

**10. Deploy Model**

Use model for desired process

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Unsupervised learning is a learning task without a outcome variable. It looks to detect the data automatically in their respective clusters, explanatory data analysis. While supervised learning tasks results in either a regression or classification, meaning that the results are predictive. 

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Descriptive models describe or illustrate characteristics of some data and visualize some trend or artifact.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

These models produce a decision for a research question or test a hypothesis. The models prefomance depends greatly on the underlying assumptions. 

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Predictive Models look to produce the most accurate predictions for a set of data. 

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model assumes the outcome variable follows a equation. Moreover, the estimates are based on a set of parameters. However, this resutlts in a model with much less complexity.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

There are no normative assumptions about the outcome variable but need more data, and takes much longer to train. 

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Parametric models are another name for mechanistic models, while nonparametric models are another name for empirically driven models. 

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

A mechanistic model is easier to determine because it is standardized to some normative equation. 

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are less flexible than empirically driven models because they empirically driven models do not follow a set of rules.

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models, which are grounded normative assumptions about relationships in the data, tend to have higher bias because they may oversimplify complex patterns, but they have lower variance, showing that predictions are stable across different samples. In contrast, empirically driven models rely on the data to uncover patterns, allowing them to achieve lower bias using nonlinearities, but this flexibility comes with higher variance, making them more sensitive to noise and prone to overfitting. 

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

The  difference between regression and classification problems is the type of outcome being predicted. In a regression problem, the target variable is continuous, while, a classification problem involves predicting a categorical outcome.

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the target variable ensures that both the training and testing sets have similar outcome distributions. This helps prevent imbalances in the data, leading to more reliable model training and more accurate evaluation of performance.

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross-validation splits data into v-folds, trains on these folds, and validates on the remaining fold, repeating this process so each fold is used once. This process is repeated multiple times, and RMSE is averaged across all runs.

This is used to get a more reliable estimate of performance by reducing dependence on any single data split by creating more splits. 

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

We might use bootstrap resampling instead of v-fold cross-validation when the dataset is small. Bootstrapping repeatedly samples with replacement from the existing data, allowing us to estimate not just RMSE and its distribution. This makes it especially useful when data is limited.

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning is the process of selecting the best hyperparameters, or, settings not learned from the data, like tree depth or learning rate, by testing different combinations and evaluating performance. We use it to improve model performance and generalization, ensuring the model is neither overfitting nor underfitting.

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

The two common performance metrics are Root Mean Squared Error (RMSE) and R-squared (R²). 

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

The two common performance metrics are Accuracy and Precision. 
:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This question is inferential because the goal is to understand the relationship between service calls and a  churn in the next month. This question is focused on interpreting a existing effect.

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This question is predictive because the goal is to predict weather a customer will churn in the next month. This question is estimating probability and forecasting an outcome. 

:::

